CHROM_COL = "Chromosome"
START_COL = "Start"
END_COL = "End"
STRAND_COL = "Strand"
MIN_COLUMNS = [CHROM_COL, START_COL, END_COL]
MIN_COLUMNS_WITH_STRAND = [*MIN_COLUMNS, STRAND_COL]

FORWARD_STRAND = "+"
REVERSE_STRAND = "-"

STRANDEDNESS_SAME = "same"
STRANDEDNESS_OPPOSITE = "opposite"
STRANDEDNESS_ANY = "any"
