CHROM_COL = "Chromosome"
START_COL = "Start"
END_COL = "End"
STRAND_COL = "Strand"
GENOME_LOC_COLS = [CHROM_COL, START_COL, END_COL]
GENOME_LOC_COLS_WITH_STRAND = [*GENOME_LOC_COLS, STRAND_COL]

FORWARD_STRAND = "+"
REVERSE_STRAND = "-"

STRANDEDNESS_SAME = "same"
STRANDEDNESS_OPPOSITE = "opposite"
STRANDEDNESS_ANY = "any"

__TEMP_INDEX_COL__ = "__temp_index__"
